[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["NODE_ENV=development npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node scripts/migrate.mjs && npm run start"
