[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["NODE_ENV=development npm install --include=dev --no-fund --no-audit --maxsockets=3"]

[phases.build]
cmds = ["/app/node_modules/.bin/vite build && /app/node_modules/.bin/esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"]

[start]
cmd = "node scripts/migrate.mjs && npm run start"
