import { useState } from 'react';
import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query';
import { Card,CardHeader,CardTitle,CardDescription,CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter } from '@/components/ui/dialog';
import { apiRequest } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';
interface Restaurant {id:string;name:string;isActive:boolean;deletedAt:string|null;hrAddonEnabled:boolean;barAddonEnabled:boolean;}
interface Draft {action:'plan'|'suspend'|'reactivate'|'delete_owner'|'restore_owner'|'addons'|'delete_restaurant'|'restore_restaurant';ownerId:string;locationId?:string;plan?:'free'|'core';hrAddonEnabled?:boolean;barAddonEnabled?:boolean;requestKey:string;reason:string;confirmation?:string;}
interface Owner {id:string;email:string;firstName:string;lastName:string;accountState:string;subscriptionPlan:string;subscriptionStatus:string;stripeSubscriptionId:string|null;restaurants:Restaurant[];pendingRequests:Array<{id:string;draft:Draft}>;}
const labels:Record<Draft['action'],string>={plan:'Change plan',suspend:'Suspend owner',reactivate:'Reactivate owner',delete_owner:'Delete owner',restore_owner:'Restore owner',addons:'Change restaurant add-ons',delete_restaurant:'Delete restaurant',restore_restaurant:'Restore restaurant'};
export function CustomerAccounts(){
 const qc=useQueryClient(),{toast}=useToast();const [search,setSearch]=useState('');
 const [draft,setDraft]=useState<Draft|null>(null),[checkoutUrl,setCheckoutUrl]=useState('');
 const query=useQuery<Owner[]>({queryKey:['/api/platform/accounts']});
 const owner=query.data?.find(o=>o.id===draft?.ownerId),restaurant=owner?.restaurants.find(l=>l.id===draft?.locationId);
 const mutation=useMutation({mutationFn:async(body:Draft)=>(await apiRequest('POST','/api/platform/accounts/manage',body)).json(),onSuccess:async result=>{setCheckoutUrl(result.checkoutUrl || '');toast({title:'Account updated',description:result.message});setDraft(null);await refresh();},onError:async()=>{await refresh();}});
 async function refresh(){await Promise.all([qc.invalidateQueries({queryKey:['/api/platform/accounts']}),qc.invalidateQueries({queryKey:['/api/platform/users']}),qc.invalidateQueries({queryKey:['/api/locations']})]);}
 function open(o:Owner,action:Draft['action'],l?:Restaurant){mutation.reset();setDraft({ownerId:o.id,action,locationId:l?.id,plan:o.subscriptionPlan==='core'?'core':'free',hrAddonEnabled:l?.hrAddonEnabled || false,barAddonEnabled:l?.barAddonEnabled || false,requestKey:crypto.randomUUID(),reason:''});}
 function field(name:keyof Draft,value:any){setDraft(d=>d?{...d,[name]:value,requestKey:crypto.randomUUID()}:d);mutation.reset();}
 const retrying=!!owner?.pendingRequests.some(p=>p.id===draft?.requestKey);
 const destructive=draft?.action==='delete_owner'||draft?.action==='delete_restaurant';
 const expected=draft?.action==='delete_owner'?owner?.email:restaurant?.name;
 return <Card className="bg-slate-800/80 border-slate-700"><CardHeader><CardTitle className="text-white">Customer accounts & restaurants</CardTitle><CardDescription>Manage customer access and Stripe subscriptions together.</CardDescription></CardHeader><CardContent className="space-y-4">
 <Input aria-label="Search customer accounts" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search owner email, name, or restaurant" className="bg-slate-900 border-slate-700"/>
 {query.isLoading?<p>Loading accounts…</p>:query.error?<div role="alert"><p>{query.error.message}</p><Button variant="outline" onClick={()=>query.refetch()}>Retry</Button></div>:!query.data?.length?<p className="text-slate-400">No customer owners have signed up yet.</p>:query.data.filter(o=>[o.email,o.firstName,o.lastName,...o.restaurants.map(l=>l.name)].join(' ').toLowerCase().includes(search.toLowerCase())).map(o=><div key={o.id} className="rounded-lg border border-slate-700 p-4 space-y-3">
 <div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium text-white">{o.email}</p><p className="text-sm text-slate-400">{[o.firstName,o.lastName].filter(Boolean).join(' ')}</p><div className="flex flex-wrap gap-2 mt-2"><Badge>{o.subscriptionPlan} · {o.subscriptionStatus}</Badge><Badge variant="outline">{o.accountState}</Badge></div></div>
 <div className="flex flex-wrap gap-2 items-start">{o.accountState==='deleted'?<Button size="sm" variant="outline" onClick={()=>open(o,'restore_owner')}>Restore owner</Button>:<><Button size="sm" variant="outline" disabled={o.accountState!=='active'||o.pendingRequests.length>0} onClick={()=>open(o,'plan')}>Change plan</Button><Button size="sm" variant="outline" disabled={o.pendingRequests.length>0} onClick={()=>open(o,o.accountState==='suspended'?'reactivate':'suspend')}>{o.accountState==='suspended'?'Reactivate':'Suspend'}</Button><Button size="sm" variant="destructive" disabled={o.pendingRequests.length>0} onClick={()=>open(o,'delete_owner')}>Delete owner</Button></>}</div></div>
 {o.pendingRequests.map(p=><div role="alert" key={p.id} className="p-3 rounded bg-amber-950 text-amber-200"><p>A billing change needs retry before another change can be made.</p><Button size="sm" variant="outline" onClick={()=>{mutation.reset();setDraft(p.draft);}}>Retry saved change</Button></div>)}
 <div className="space-y-2">{o.restaurants.length?o.restaurants.map(l=><div key={l.id} className="flex flex-wrap justify-between gap-2 rounded bg-slate-900/60 p-3"><div><p className="text-white">{l.name}</p><p className="text-xs text-slate-400">{l.deletedAt?'Deleted':l.isActive?'Active':'Inactive'} · HR {l.hrAddonEnabled?'on':'off'} · Bar {l.barAddonEnabled?'on':'off'}</p></div><div className="flex flex-wrap gap-2">{l.deletedAt||!l.isActive?<Button size="sm" variant="outline" disabled={o.accountState!=='active'||!!o.pendingRequests.length} onClick={()=>open(o,'restore_restaurant',l)}>Restore</Button>:<><Button size="sm" variant="outline" disabled={o.accountState!=='active'||!!o.pendingRequests.length} onClick={()=>open(o,'addons',l)}>Add-ons</Button><Button size="sm" variant="destructive" disabled={!!o.pendingRequests.length} onClick={()=>open(o,'delete_restaurant',l)}>Delete</Button></>}</div></div>):<p className="text-sm text-slate-400">No restaurants.</p>}</div>
 </div>)}
 {checkoutUrl && <div className="space-y-2 p-4 border border-green-800 rounded"><p className="text-green-300">Customer checkout link — share with the owner to complete their upgrade.</p><Input aria-label="Customer checkout link" readOnly value={checkoutUrl}/><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(checkoutUrl);toast({title:'Checkout link copied'});}catch{toast({title:'Select and copy the link manually'});}}}>Copy link</Button></div>}
 <Dialog open={!!draft} onOpenChange={open=>{if(!open && !mutation.isPending)setDraft(null);}}><DialogContent className="bg-slate-900 border-slate-700 text-white max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{draft?labels[draft.action]:''}</DialogTitle><DialogDescription>{restaurant?.name || owner?.email}</DialogDescription></DialogHeader>
 {draft && <div className="space-y-4">
 {draft.action==='plan' && <label className="block">Plan<select aria-label="Owner plan" className="w-full p-2 mt-1 bg-slate-800 border border-slate-700 rounded" value={draft.plan} disabled={mutation.isPending || retrying} onChange={e=>field('plan',e.target.value)}><option value="free">Free — restricted access</option><option value="core">Core — paid subscription</option></select><p className="mt-2 text-sm text-slate-400">Core requires payment through checkout if there is no active subscription. Free cancels the subscription and add-ons immediately, with no automatic refund. Free supports one active restaurant.</p></label>}
 {draft.action==='addons' && <><label className="flex gap-2"><input type="checkbox" checked={draft.hrAddonEnabled} disabled={mutation.isPending || retrying} onChange={e=>field('hrAddonEnabled',e.target.checked)}/> HR add-on</label><label className="flex gap-2"><input type="checkbox" checked={draft.barAddonEnabled} disabled={mutation.isPending || retrying} onChange={e=>field('barAddonEnabled',e.target.checked)}/> Bar & Beverage add-on</label><p className="text-sm text-slate-400">Stripe applies prorated charges or credits immediately. A failed payment leaves access unchanged.</p></>}
 {draft.action==='suspend' && <p>Blocks owner and restaurant access and pauses new subscription invoices. Existing invoices remain unchanged.</p>}
 {draft.action==='reactivate' && <p>Restores account access and resumes billing for an existing subscription. A cancelled subscription requires a new checkout.</p>}
 {destructive && <><p className="text-sm">{draft.action==='delete_owner'?'Blocks the owner and all their restaurants, cancels their subscription, and stops future subscription charges.':'Removes this restaurant from customer access and removes its paid add-ons. The owner’s Core subscription continues.'} Records are retained for restoration and history; this does not permanently erase data or issue a refund.</p><label className="block">Type <strong>{expected}</strong> to confirm<Input aria-label="Deletion confirmation" value={draft.confirmation || ''} disabled={mutation.isPending || retrying} onChange={e=>field('confirmation',e.target.value)}/></label></>}
 {draft.action.startsWith('restore') && <p>Restores access without enabling add-ons or restarting cancelled subscriptions. Restore each deleted restaurant separately.</p>}
 <label className="block">Reason<Input aria-label="Reason for account change" value={draft.reason} maxLength={500} disabled={mutation.isPending || retrying} onChange={e=>field('reason',e.target.value)} placeholder="Required for the admin history"/></label>
 {mutation.error && <p role="alert" className="text-red-400">{mutation.error.message}</p>}
 </div>}
 <DialogFooter><Button variant="outline" disabled={mutation.isPending} onClick={()=>setDraft(null)}>Cancel</Button><Button variant={destructive?'destructive':'default'} disabled={!draft?.reason.trim() || mutation.isPending || (destructive && draft?.confirmation!==expected)} onClick={()=>draft && mutation.mutate(draft)}>{mutation.isPending?'Updating access and billing…':'Confirm change'}</Button></DialogFooter>
 </DialogContent></Dialog>
 </CardContent></Card>;
}
